/**
 * Insurance providers marketplace - multiple companies with different plans
 */
module.exports = [
  {
    id: 'safecover',
    name: 'SafeCover',
    legal_entity_name: 'SafeCover Insurance Ltd',
    registered_address: '123 Insurance House, London EC2V 7HH, United Kingdom',
    fca_registration_number: '123456',
    claims_phone: '0800 123 4567',
    enquiries_email: 'enquiries@safecover.co.uk',
    claims_email: 'claims@safecover.co.uk',
    logo: '🛡️',
    tagline: 'Trusted by 50k+ merchants',
    commission_rate: 0.15,
    terms_url: '/terms.html?provider=safecover',
    plans: [
      { id: 'basic', name: 'Basic', coverage: 500, excess: 25, premium_rate: 0.002, benefits: ['Loss & damage', '7 days'],
        summary: 'Covers loss, damage or theft of goods during transit. Policy active from dispatch to delivery.' },
      { id: 'standard', name: 'Standard', coverage: 1000, excess: 50, premium_rate: 0.003, benefits: ['Loss, damage, theft', '14 days', 'Priority claims'],
        summary: 'Extended transit protection including theft. 14-day coverage with priority claims handling.' },
      { id: 'premium', name: 'Premium', coverage: 2500, excess: 75, premium_rate: 0.005, benefits: ['Full coverage', '30 days', '24/7 support', 'Express payout'],
        summary: 'Comprehensive coverage for 30 days. 24/7 support and express payout on approved claims.' },
    ],
  },
  {
    id: 'shieldpro',
    name: 'ShieldPro',
    legal_entity_name: 'ShieldPro Underwriting Ltd',
    registered_address: '88 City Road, London EC1V 2NX, United Kingdom',
    fca_registration_number: '234567',
    claims_phone: '0800 234 5678',
    enquiries_email: 'hello@shieldpro.example',
    claims_email: 'claims@shieldpro.example',
    logo: '🔒',
    tagline: 'Enterprise-grade protection',
    commission_rate: 0.12,
    terms_url: '/terms.html?provider=shieldpro',
    plans: [
      { id: 'essential', name: 'Essential', coverage: 750, excess: 35, premium_rate: 0.0025, benefits: ['Transit protection', '10 days'],
        summary: 'Goods-in-transit protection for loss or damage. 10-day coverage from shipment.' },
      { id: 'plus', name: 'Plus', coverage: 1500, excess: 60, premium_rate: 0.004, benefits: ['Extended coverage', '21 days', 'Dedicated support'],
        summary: 'Extended coverage period with dedicated claims support. Includes accidental damage.' },
      { id: 'max', name: 'Max', coverage: 5000, excess: 100, premium_rate: 0.006, benefits: ['Unlimited claims', '60 days', 'White-glove service'],
        summary: 'Maximum protection with 60-day coverage. White-glove claims service and unlimited claims.' },
    ],
  },
  {
    id: 'covermax',
    name: 'CoverMax',
    legal_entity_name: 'CoverMax Insurance Ltd',
    registered_address: '1 Cover Street, Manchester M1 1AA, United Kingdom',
    fca_registration_number: '345678',
    claims_phone: '0800 345 6789',
    enquiries_email: 'enquiries@safecover.co.uk',
    claims_email: 'claims@covermax.example',
    logo: '⚡',
    tagline: 'Fast claims, low prices',
    commission_rate: 0.18,
    terms_url: '/terms.html?provider=covermax',
    plans: [
      { id: 'starter', name: 'Starter', coverage: 300, excess: 25, premium_rate: 0.0015, benefits: ['Basic protection', '5 days'],
        summary: 'Essential transit cover for loss or damage. 5-day policy from delivery date.' },
      { id: 'pro', name: 'Pro', coverage: 1000, excess: 50, premium_rate: 0.003, benefits: ['Standard coverage', '14 days', 'Same-day claims'],
        summary: 'Standard transit insurance with same-day claims processing. 14-day coverage.' },
      { id: 'elite', name: 'Elite', coverage: 3000, excess: 80, premium_rate: 0.0045, benefits: ['Premium coverage', '30 days', 'Instant payout'],
        summary: 'Premium protection with instant payout on approved claims. 30-day coverage.' },
    ],
  },
  {
    id: 'assurex',
    name: 'AssureX',
    legal_entity_name: 'AssureX Insurance Ltd',
    registered_address: '200 Assurance Wharf, Edinburgh EH1 1YZ, United Kingdom',
    fca_registration_number: '456789',
    claims_phone: '0800 456 7890',
    enquiries_email: 'support@assurex.example',
    claims_email: 'claims@assurex.example',
    logo: '✓',
    tagline: 'Simple, transparent coverage',
    commission_rate: 0.14,
    terms_url: '/terms.html?provider=assurex',
    plans: [
      { id: 'lite', name: 'Lite', coverage: 400, excess: 30, premium_rate: 0.002, benefits: ['Essential cover', '7 days'],
        summary: 'Basic transit protection for loss or damage. Simple claims process, 7-day coverage.' },
      { id: 'core', name: 'Core', coverage: 1200, excess: 55, premium_rate: 0.0035, benefits: ['Full protection', '14 days', 'Easy claims'],
        summary: 'Full transit protection with easy online claims. 14-day coverage period.' },
      { id: 'ultimate', name: 'Ultimate', coverage: 4000, excess: 90, premium_rate: 0.005, benefits: ['Maximum coverage', '45 days', 'Concierge support'],
        summary: 'Maximum coverage with concierge claims support. 45-day protection period.' },
    ],
  },
];
