/**
 * SafeCover scenarios - coverage configs per industry
 */
module.exports = {
  logistics: {
    id: 'logistics',
    name: 'Logistics & Shipping',
    icon: '📦',
    coverage_type: 'goods-in-transit',
    max_value: 5000,
    duration: '14 days',
    premium_rate: 0.003,
    benefits: [
      'Covers loss, damage, or theft during delivery',
      'Real-time tracking protection',
      'Up to $5,000 coverage',
    ],
    label: 'Add shipping protection',
    cart_label: 'Shipping Protection',
  },
  healthcare: {
    id: 'healthcare',
    name: 'Healthcare',
    icon: '🏥',
    coverage_type: 'appointment-protection',
    max_value: 500,
    duration: '30 days',
    premium_rate: 0.02,
    benefits: [
      'Covers no-show and cancellation fees',
      'Telemedicine visit protection',
      'Up to $500 per appointment',
    ],
    label: 'Add appointment protection',
    cart_label: 'Appointment Protection',
  },
  hospitality: {
    id: 'hospitality',
    name: 'Hospitality & Travel',
    icon: '🏨',
    coverage_type: 'trip-cancellation',
    max_value: 2000,
    duration: 'Trip duration',
    premium_rate: 0.025,
    benefits: [
      'Cancel for any reason coverage',
      'Hotel & flight protection',
      'Up to $2,000 reimbursement',
    ],
    label: 'Add trip protection',
    cart_label: 'Trip Protection',
  },
  food: {
    id: 'food',
    name: 'Food & Delivery',
    icon: '🍔',
    coverage_type: 'delivery-guarantee',
    max_value: 200,
    duration: '24 hours',
    premium_rate: 0.015,
    benefits: [
      'Wrong order or late delivery refund',
      'Food quality guarantee',
      'Up to $200 coverage',
    ],
    label: 'Add delivery guarantee',
    cart_label: 'Delivery Guarantee',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber & Digital',
    icon: '🔒',
    coverage_type: 'data-breach-protection',
    max_value: 1000,
    duration: '12 months',
    premium_rate: 0.05,
    benefits: [
      'Identity theft monitoring',
      'Data breach response support',
      'Up to $1,000 recovery',
    ],
    label: 'Add cyber protection',
    cart_label: 'Cyber Protection',
  },
  mobility: {
    id: 'mobility',
    name: 'Mobility & Gig Economy',
    icon: '🚗',
    coverage_type: 'per-trip-accident',
    max_value: 1000,
    duration: 'Trip duration',
    premium_rate: 0.008,
    benefits: [
      'Per-ride accident cover',
      'Third-party liability',
      'Up to $1,000 per trip',
    ],
    label: 'Add trip insurance',
    cart_label: 'Trip Insurance',
  },
  parametric: {
    id: 'parametric',
    name: 'Parametric (Climate/Events)',
    icon: '🌦️',
    coverage_type: 'parametric-trigger',
    max_value: 500,
    duration: 'Event period',
    premium_rate: 0.02,
    benefits: [
      'Auto-payout on trigger',
      'Weather/delay protection',
      'No claims paperwork',
    ],
    label: 'Add parametric cover',
    cart_label: 'Parametric Cover',
  },
  retail: {
    id: 'retail',
    name: 'Retail & E-commerce',
    icon: '🛒',
    coverage_type: 'goods-in-transit',
    max_value: 1000,
    duration: '7 days',
    premium_rate: 0.003,
    benefits: [
      'Covers loss, damage, or theft during delivery',
      'Instant policy activation',
      'Up to $1,000 coverage',
    ],
    label: 'Add protection',
    cart_label: 'SafeCover Insurance',
  },
  gadgets: {
    id: 'gadgets',
    name: 'Gadgets & Electronics',
    icon: '📱',
    coverage_type: 'device-protection',
    max_value: 1500,
    duration: '12 months',
    premium_rate: 0.02,
    benefits: [
      'Accidental damage & theft',
      'Screen crack replacement',
      'Up to $1,500 coverage',
    ],
    label: 'Add device protection',
    cart_label: 'Device Protection',
  },
  events: {
    id: 'events',
    name: 'Events & Ticketing',
    icon: '🎫',
    coverage_type: 'ticket-protection',
    max_value: 300,
    duration: 'Event date',
    premium_rate: 0.04,
    benefits: [
      'Cancel for any reason refund',
      'No-show protection',
      'Up to $300 per ticket',
    ],
    label: 'Add ticket protection',
    cart_label: 'Ticket Protection',
  },
};
